name: Create release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    name: PyPI Release
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install build dependencies
        run: |
          pip install -U pip
          pip install build twine

      - name: Build distribution
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # twine check dist/*
          # twine upload dist/*

  github-release:
    runs-on: ubuntu-latest
    name: GitHub release
    environment: release
    permissions:
      contents: write # for softprops/action-gh-release to create GitHub release
    steps:
      - uses: actions/checkout@v4
      - name: Get release version
        id: get_version
        uses: actions/github-script@v7
        with:
          script: core.setOutput('version', context.ref.replace("refs/tags/v", ""))

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "MSTeams Connector ${{ steps.get_version.outputs.version }}"
          body: "Changelog: https://github.com/cloud-bees/msteams-connector/CHANGELOG.md"
